Fix: tests/conftest> limit lenght of float to 32 bit
This would prevent errors like

```
>       assert (a + b) + c == a + (b + c)
E       assert Coord(0.0, 8192.000000000007) == Coord(0.0,
8192.000000000005)
E         -Coord(0.0, 8192.000000000007)
E         +Coord(0.0, 8192.000000000005)
```

Which was occurred due to floating point calculation problem